<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>NewHeap.Platform.Media</PackageId>
    <Version>0.1.0</Version>
    <Copyright>NewHeap B.V.</Copyright>
    <Title>NewHeap Media</Title>
    <PackageProjectUrl>https://github.com/NewHeap/NewHeap-Platform</PackageProjectUrl>
    <RepositoryUrl>https://github.com/NewHeap/NewHeap-Platform</RepositoryUrl>
    <IncludeSymbols>True</IncludeSymbols>
    <EmbedAllSources>True</EmbedAllSources>
    <DebugType>Embedded</DebugType>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NewHeap.Platform.Media.Core\NewHeap.Platform.Media.Core.csproj" />
    <ProjectReference Include="..\NewHeap.Platform.Media.FileStructureStorage.SqlServer\NewHeap.Platform.Media.FileStructureStorage.SqlServer.csproj" />
    <ProjectReference Include="..\NewHeap.Platform.Media.Http\NewHeap.Platform.Media.Http.csproj" />
    <ProjectReference Include="..\NewHeap.Platform.Media.MediaStorage.FileSystem\NewHeap.Platform.Media.MediaStorage.FileSystem.csproj" />
  </ItemGroup>
</Project>
