<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DotNetCore.CAP" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\NewHeap.Platform.AspNet.Common\NewHeap.Platform.AspNet.Common.csproj" />
      <ProjectReference Include="..\NewHeap.Platform.Common\NewHeap.Platform.Common.csproj" />
    </ItemGroup>

</Project>
