<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NewHeap.Platform.Media.Core\NewHeap.Platform.Media.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" />
      <PackageReference Include="AWSSDK.SecurityToken" />
      <PackageReference Include="AWSSDK.SSO" />
      <PackageReference Include="AWSSDK.SSOOIDC" />
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
      <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

</Project>
