<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>NewHeap.Media.Http</PackageId>
        <Version>0.1.0</Version>
        <Copyright>NewHeap B.V.</Copyright>
        <Title>NewHeap Media Http</Title>
        <PackageProjectUrl>https://dev.azure.com/NewHeap/NewHeap-Platform</PackageProjectUrl>
        <RepositoryUrl>https://dev.azure.com/NewHeap/_git/NewHeap-Platform</RepositoryUrl>
        <RootNamespace>NhMedia.Http</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NewHeap.Media.Core\NewHeap.Media.Core.csproj" />
    </ItemGroup>

</Project>
