<Project>
  <PropertyGroup Condition="'$(IsPackable)' != 'false'">
    <_ProjectPackageReadme Condition="Exists('$(MSBuildProjectDirectory)\README.md')">README.md</_ProjectPackageReadme>
    <_ProjectPackageReadme Condition="'$(_ProjectPackageReadme)' == '' and Exists('$(MSBuildProjectDirectory)\readme.md')">readme.md</_ProjectPackageReadme>
    <_RepositoryPackageReadme>$(MSBuildThisFileDirectory)..\..\README.md</_RepositoryPackageReadme>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false' and '$(_ProjectPackageReadme)' != ''">
    <None Include="$(MSBuildProjectDirectory)\$(_ProjectPackageReadme)"
          Pack="true"
          PackagePath="README.md"
          Visible="false" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsPackable)' != 'false' and '$(_ProjectPackageReadme)' == ''">
    <None Include="$(MSBuildThisFileDirectory)..\..\README.md"
          Pack="true"
          PackagePath="README.md"
          Visible="false" />
  </ItemGroup>
</Project>
