<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AutoMapper" Version="14.0.0" />
    <PackageVersion Include="AutoMapper.Collection" Version="11.0.0" />
    <PackageVersion Include="DotNetCore.CAP" Version="8.3.5" />
    <PackageVersion Include="DotNetCore.CAP.RabbitMQ" Version="8.3.5" />
    <PackageVersion Include="DotNetCore.CAP.SqlServer" Version="8.3.5" />
    <PackageVersion Include="Hangfire" Version="1.8.18" />
    <PackageVersion Include="Hangfire.Console" Version="1.4.3" />
    <PackageVersion Include="KeyedSemaphores" Version="5.0.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="9.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.3" />
    <PackageVersion Include="Microsoft.OpenApi" Version="1.6.23" />
    <PackageVersion Include="OneOf" Version="3.0.271" />
    <PackageVersion Include="OpenTelemetry" Version="1.11.2" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.1" />
    <PackageVersion Include="Sentry" Version="5.14.1" />
    <PackageVersion Include="Sentry.AspNetCore" Version="5.14.1" />
    <PackageVersion Include="Sentry.Extensions.Logging" Version="5.14.1" />
    <PackageVersion Include="StackExchange.Utils.Configuration" Version="0.1.12" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.1.0" />
    <PackageVersion Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.3" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.3" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageVersion Include="Azure.Identity" Version="1.13.2" />
    <PackageVersion Include="EPPlus" Version="4.5.3.3" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="9.6.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Identity.Core" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="9.0.3" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.1.4" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="8.1.0" />
    <PackageVersion Include="System.Formats.Asn1" Version="9.0.3" />
    <PackageVersion Include="System.IO.Pipelines" Version="9.0.3" />
    <PackageVersion Include="System.Net.Http" Version="4.3.4" />
    <PackageVersion Include="System.Text.Json" Version="9.0.3" />
    <PackageVersion Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
    <PackageVersion Include="NeoSmart.Caching.Sqlite.AspNetCore" Version="9.0.1" />
    <PackageVersion Include="ZiggyCreatures.FusionCache" Version="2.1.0" />
    <PackageVersion Include="ZiggyCreatures.FusionCache.Serialization.NewtonsoftJson" Version="2.1.0" />
  </ItemGroup>
</Project>