<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="SSH.NET" PrivateAssets="all" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Applications/SampleProjectManagement.Api/SampleProjectManagement.Api.csproj" />
    <ProjectReference Include="../../Applications/SampleProjectManagement.DatabaseRead.Mcp/SampleProjectManagement.DatabaseRead.Mcp.csproj" />
    <ProjectReference Include="../../Libraries/SampleProjectManagement.Core/SampleProjectManagement.Core.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Libraries/NewHeap.Platform.Common.Test/NewHeap.Platform.Common.Test.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Libraries/NewHeap.Platform.AspNet.Common.Test/NewHeap.Platform.AspNet.Common.Test.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Libraries/NewHeap.Platform.AI.Test/NewHeap.Platform.AI.Test.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Libraries/NewHeap.Platform.AI.Mcp/NewHeap.Platform.AI.Mcp.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Libraries/NewHeap.Platform.AI.AgentFramework/NewHeap.Platform.AI.AgentFramework.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Tools/NewHeap.Platform.DatabaseRead.Tool/NewHeap.Platform.DatabaseRead.Tool.csproj" />
  </ItemGroup>
</Project>
