<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>NewHeap Common</Title>
        <Copyright>NewHeap B.V.</Copyright>
        <PackageProjectUrl>https://dev.azure.com/NewHeap/NewHeap-Platform</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://dev.azure.com/NewHeap/_git/NewHeap-Platform</RepositoryUrl>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<!-- If all members are not documented, you can disable the compiler warnings -->
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<IncludeSymbols>True</IncludeSymbols>
		<EmbedAllSources>True</EmbedAllSources>
		<DebugType>Embedded</DebugType>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageIcon>NH_logo.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\..\Assets\NH_logo.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="Hangfire" />
        <PackageReference Include="Hangfire.Console" />
        <PackageReference Include="KeyedSemaphores" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="OpenTelemetry" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" />
        <PackageReference Include="StackExchange.Utils.Configuration" />
        <PackageReference Include="System.Linq.Dynamic.Core" />
    </ItemGroup>

    <ItemGroup>
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
