<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SampleProjectManagement.DAL/SampleProjectManagement.DAL.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Libraries/NewHeap.Platform.AspNet.Common/NewHeap.Platform.AspNet.Common.csproj" />
    <ProjectReference Include="../../../../../../src/Back-end/Libraries/NewHeap.Platform.Mapping/NewHeap.Platform.Mapping.csproj" />
  </ItemGroup>
</Project>
