<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>NewHeap.Platform.Media.FileStructureStorage.SqlServer</PackageId>
        <Version>0.1.0</Version>
        <Copyright>NewHeap B.V.</Copyright>
        <Title>NewHeap Media SqlServer FileStructure Storage</Title>
        <PackageProjectUrl>https://dev.azure.com/NewHeap/NewHeap-Platform</PackageProjectUrl>
        <RepositoryUrl>https://dev.azure.com/NewHeap/_git/NewHeap-Platform</RepositoryUrl>        
        <RootNamespace>NewHeap.Media.FileStructureStorage.SqlServer</RootNamespace>
        <IncludeSymbols>True</IncludeSymbols>
        <EmbedAllSources>True</EmbedAllSources>
        <DebugType>Embedded</DebugType>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <IsPackable>True</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NewHeap.Platform.Media.Core\NewHeap.Platform.Media.Core.csproj" />      
    </ItemGroup>

    <ItemGroup>
        <None Include="readme.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
    
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    </ItemGroup>

</Project>
