<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>NewHeap.Platform.Media.FileStructureStorage.SqlServer</PackageId>
        <Copyright>NewHeap B.V.</Copyright>
        <Title>NewHeap Media SqlServer FileStructure Storage</Title>
        <PackageDescription>SQL Server file-structure persistence, registration, and migrations for NewHeap Platform media libraries.</PackageDescription>
        <PackageTags>newheap platform media storage entity-framework sql-server</PackageTags>
        <RootNamespace>NewHeap.Media.FileStructureStorage.SqlServer</RootNamespace>
        <IsPackable>True</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NewHeap.Platform.Media.Core\NewHeap.Platform.Media.Core.csproj" />      
    </ItemGroup>
    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    </ItemGroup>

</Project>
