<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>NewHeap.Platform.Media.MediaStorage.FileSystem</PackageId>
        <Version>0.1.0</Version>
        <Copyright>NewHeap B.V.</Copyright>
        <Title>NewHeap Media FileSystem Storage</Title>
        <PackageProjectUrl>https://dev.azure.com/NewHeap/NewHeap-Platform</PackageProjectUrl>
        <RepositoryUrl>https://dev.azure.com/NewHeap/_git/NewHeap-Platform</RepositoryUrl>
        <Copyright>Copyright © NewHeap 2025</Copyright>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NewHeap.Platform.Media.Core\NewHeap.Platform.Media.Core.csproj" />      
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

</Project>
