<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>NewHeap.Platform.Media.MediaStorage.FileSystem</PackageId>
        <Title>NewHeap Media FileSystem Storage</Title>
        <Copyright>NewHeap B.V.</Copyright>
        <PackageDescription>Local file-system blob storage for NewHeap Platform media libraries.</PackageDescription>
        <PackageTags>newheap platform media storage filesystem</PackageTags>
        <IsPackable>True</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\NewHeap.Platform.Media.Core\NewHeap.Platform.Media.Core.csproj" />      
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    
    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" />
      <PackageReference Include="Microsoft.Extensions.Options" />
    </ItemGroup>

</Project>
