<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Copyright>NewHeap B.V.</Copyright>
	<Title>NewHeap ASP.NET Common reusable test helpers</Title>
	<PackageDescription>Reusable ASP.NET Core and Entity Framework test helpers for applications built with NewHeap.Platform.AspNet.Common.</PackageDescription>
	<PackageTags>newheap platform aspnetcore testing entity-framework</PackageTags>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<!-- If all members are not documented, you can disable the compiler warnings -->
	<NoWarn>$(NoWarn);CS1591</NoWarn>
	<IsPackable>true</IsPackable>
	<IsTestProject>false</IsTestProject>
  </PropertyGroup>

<ItemGroup>
	<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewHeap.Platform.AspNet.Common\NewHeap.Platform.AspNet.Common.csproj" />
    <ProjectReference Include="..\NewHeap.Platform.Common.Test\NewHeap.Platform.Common.Test.csproj" />
  </ItemGroup>

</Project>
