<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Copyright>NewHeap B.V.</Copyright>
	<Title>NewHeap Common reusable test helpers</Title>
	<PackageProjectUrl>https://github.com/NewHeap/NewHeap-Platform</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/NewHeap/NewHeap-Platform</RepositoryUrl>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<!-- If all members are not documented, you can disable the compiler warnings -->
	<NoWarn>$(NoWarn);CS1591</NoWarn>
	<IncludeSymbols>True</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<EmbedAllSources>True</EmbedAllSources>
	<DebugType>Embedded</DebugType>
	<PackageIcon>NH_logo.png</PackageIcon>
	<IsPackable>true</IsPackable>
	<IsTestProject>false</IsTestProject>
  </PropertyGroup>

	<ItemGroup>
		<None Include="..\..\Assets\NH_logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	
   <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="xunit" />
  </ItemGroup>
	
   <ItemGroup>
     <ProjectReference Include="..\NewHeap.Platform.Common\NewHeap.Platform.Common.csproj" />
   </ItemGroup>
	
   <ItemGroup>
     <None Update="README.md">
       <PackagePath>\</PackagePath>
       <Pack>True</Pack>
     </None>
   </ItemGroup>
</Project>
