<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Copyright>NewHeap B.V.</Copyright>
        <Title>NewHeap AspNet Common</Title>
        <PackageProjectUrl>https://github.com/NewHeap/NewHeap-Platform</PackageProjectUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/NewHeap/NewHeap-Platform</RepositoryUrl>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
		<!-- If all members are not documented, you can disable the compiler warnings -->
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<EmbedAllSources>True</EmbedAllSources>
		<DebugType>Embedded</DebugType>
		<PackageIcon>NH_logo.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>
    <PropertyGroup>
        <NoWarn>CS1998,CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\..\Assets\NH_logo.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire" />
        <PackageReference Include="Hangfire.Console" />
        <PackageReference Include="Hangfire.PostgreSql" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Microsoft.OpenApi" />
        <PackageReference Include="OneOf" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="Sentry.AspNetCore" />
        <PackageReference Include="System.Linq.Dynamic.Core" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NewHeap.Platform.Common\NewHeap.Platform.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\Translations\" />
    </ItemGroup>
</Project>
