// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewHeap.Media.FileStructureStorage.SqlServer;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewHeap.Media.FileStructureStorage.PostgreSql.Migrations
{
    [DbContext(typeof(FileStructureDbContext))]
    partial class FileStructureDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nhmedia")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewHeap.Media.FileStructureStorage.SqlServer.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Creator")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MetaData")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Path")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<byte[]>("PathLookupHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PathNameLookupHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PathLookupHash")
                        .HasDatabaseName("IX_Files_PathLookupHash");

                    b.HasIndex("PathNameLookupHash")
                        .HasDatabaseName("IX_Files_PathNameLookupHash");

                    b.ToTable("Files", "nhmedia");
                });

            modelBuilder.Entity("NewHeap.Media.FileStructureStorage.SqlServer.Entities.FolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Path")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<byte[]>("PathLookupHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PathNameLookupHash")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("PathLookupHash")
                        .HasDatabaseName("IX_Folders_PathLookupHash");

                    b.HasIndex("PathNameLookupHash")
                        .HasDatabaseName("IX_Folders_PathNameLookupHash");

                    b.ToTable("Folders", "nhmedia");
                });

            modelBuilder.Entity("NewHeap.Media.FileStructureStorage.SqlServer.Entities.Localization", b =>
                {
                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("TypeName", "EntityId", "Language", "PropertyName");

                    b.HasIndex("TypeName", "EntityId", "Language");

                    b.ToTable("Localizations", "nhmedia");
                });
#pragma warning restore 612, 618
        }
    }
}
