// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewHeap.Media.FileStructureStorage.SqlServer;

#nullable disable

namespace NewHeap.Media.FileStructureStorage.SqlServer.Migrations
{
    [DbContext(typeof(FileStructureDbContext))]
    [Migration("20260606154446_IndexedMediaLibraryLookups")]
    partial class IndexedMediaLibraryLookups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nhmedia")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewHeap.Media.FileStructureStorage.SqlServer.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltText")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Creator")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaData")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Path")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PathLookupHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("binary(32)")
                        .HasComputedColumnSql("CONVERT(binary(32), HASHBYTES('SHA2_256', LOWER(COALESCE([Path], N''))))", true);

                    b.Property<byte[]>("PathNameLookupHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("binary(32)")
                        .HasComputedColumnSql("CONVERT(binary(32), HASHBYTES('SHA2_256', CONCAT(LOWER(COALESCE([Path], N'')), NCHAR(31), LOWER(COALESCE([Name], N'')))))", true);

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PathLookupHash")
                        .HasDatabaseName("IX_Files_PathLookupHash");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PathLookupHash"), new[] { "Id" });

                    b.HasIndex("PathNameLookupHash")
                        .HasDatabaseName("IX_Files_PathNameLookupHash");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PathNameLookupHash"), new[] { "Id" });

                    b.ToTable("Files", "nhmedia");
                });

            modelBuilder.Entity("NewHeap.Media.FileStructureStorage.SqlServer.Entities.FolderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Path")
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PathLookupHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("binary(32)")
                        .HasComputedColumnSql("CONVERT(binary(32), HASHBYTES('SHA2_256', LOWER(COALESCE([Path], N''))))", true);

                    b.Property<byte[]>("PathNameLookupHash")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("binary(32)")
                        .HasComputedColumnSql("CONVERT(binary(32), HASHBYTES('SHA2_256', CONCAT(LOWER(COALESCE([Path], N'')), NCHAR(31), LOWER(COALESCE([Name], N'')))))", true);

                    b.HasKey("Id");

                    b.HasIndex("PathLookupHash")
                        .HasDatabaseName("IX_Folders_PathLookupHash");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PathLookupHash"), new[] { "Id" });

                    b.HasIndex("PathNameLookupHash")
                        .HasDatabaseName("IX_Folders_PathNameLookupHash");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PathNameLookupHash"), new[] { "Id" });

                    b.ToTable("Folders", "nhmedia");
                });

            modelBuilder.Entity("NewHeap.Media.FileStructureStorage.SqlServer.Entities.Localization", b =>
                {
                    b.Property<string>("TypeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Language")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("TypeName", "EntityId", "Language", "PropertyName");

                    b.HasIndex("TypeName", "EntityId", "Language");

                    b.ToTable("Localizations", "nhmedia");
                });
#pragma warning restore 612, 618
        }
    }
}
