// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SampleProjectManagement.DAL;

#nullable disable

namespace SampleProjectManagement.DAL.Migrations
{
    [DbContext(typeof(SampleProjectManagementDbContext))]
    [Migration("20260824214941_AddNhBackgroundOperations")]
    partial class AddNhBackgroundOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelRequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConcurrencyKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentAttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("DiagnosticCorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DispatchGeneration")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DomainObjectId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DomainObjectType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureMessageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FanOutItemKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FanOutKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastProjectedNotificationEventSequence")
                        .HasColumnType("bigint");

                    b.Property<long>("LatestEventSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("NextDispatchAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PayloadSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessorKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ProgressCurrent")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProgressMessageArgumentsJson")
                        .HasColumnType("text");

                    b.Property<string>("ProgressMessageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("ProgressPercentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ProgressPhaseKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("ProgressTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ResultReferenceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResultReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResultUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RootOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchedulerJobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("SensitiveDataRedactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserNotificationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ParentOperationId");

                    b.HasIndex("RootOperationId");

                    b.HasIndex("SchedulerJobId");

                    b.HasIndex("UserNotificationId");

                    b.HasIndex("Status", "CompletedAt");

                    b.HasIndex("Status", "HeartbeatAt");

                    b.HasIndex("DivisionId", "Status", "LastModifiedDateTime");

                    b.HasIndex("OwnerUserId", "Status", "LastModifiedDateTime");

                    b.HasIndex("ParentOperationId", "FanOutKey", "FanOutItemKey")
                        .IsUnique();

                    b.HasIndex("ProcessorKey", "Status", "NextDispatchAt", "Priority", "CreationDateTime");

                    b.ToTable("BackgroundOperations");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiagnosticCorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DispatchGeneration")
                        .HasColumnType("integer");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecoveryReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SchedulerJobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "AttemptNumber")
                        .IsUnique();

                    b.HasIndex("OperationId", "StartedAt");

                    b.ToTable("BackgroundOperationAttempts");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationCheckpoint", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CheckpointKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("OperationId", "CheckpointKey");

                    b.ToTable("BackgroundOperationCheckpoints");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMilestone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOperatorOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageArgumentsJson")
                        .HasColumnType("text");

                    b.Property<string>("MessageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultReferenceId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ResultReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResultUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<long>("SnapshotVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uuid");

                    b.Property<string>("StepKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "CreationDateTime");

                    b.HasIndex("OperationId", "Sequence")
                        .IsUnique();

                    b.ToTable("BackgroundOperationEvents");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationIdempotencyRecord", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.HasKey("Scope", "KeyHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OperationId");

                    b.ToTable("BackgroundOperationIdempotencyRecords");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationLease", b =>
                {
                    b.Property<string>("ResourceKey")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<int>("Slot")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FencingToken")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("ResourceKey", "Slot");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OperationId");

                    b.ToTable("BackgroundOperationLeases");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("ActiveItems")
                        .HasColumnType("bigint");

                    b.Property<int>("AggregationMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ContinueOnChildFailure")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Current")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("CurrentAttemptId")
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<long>("DiscoveredItems")
                        .HasColumnType("bigint");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<long>("FailedItems")
                        .HasColumnType("bigint");

                    b.Property<long>("FencingVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageArgumentsJson")
                        .HasColumnType("text");

                    b.Property<string>("MessageKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentStepId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Percentage")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("ProcessedItems")
                        .HasColumnType("bigint");

                    b.Property<long>("RetriedItems")
                        .HasColumnType("bigint");

                    b.Property<long>("SkippedItems")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("SucceededItems")
                        .HasColumnType("bigint");

                    b.Property<string>("TitleArgumentsJson")
                        .HasColumnType("text");

                    b.Property<string>("TitleKey")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Weight")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ParentStepId");

                    b.HasIndex("OperationId", "DisplayOrder", "Status");

                    b.HasIndex("OperationId", "ParentStepId", "StepKey")
                        .IsUnique();

                    b.ToTable("BackgroundOperationSteps");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("UserSelectAllowed")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("DivisionRoles");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionRoleClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DivisionRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DivisionRoleId");

                    b.ToTable("DivisionRoleClaims");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockOutEndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockOutStartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DivisionId", "UserId")
                        .IsUnique();

                    b.ToTable("DivisionUsers");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionUserRole", b =>
                {
                    b.Property<Guid>("DivisionUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DivisionRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("DivisionUserId", "DivisionRoleId");

                    b.HasIndex("DivisionRoleId");

                    b.ToTable("DivisionUserRoles");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("text");

                    b.Property<bool>("AdditionalDataProcessed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ObjectType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ObjectTypeFull")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("Tag");

                    b.HasIndex("UserId");

                    b.HasIndex("ObjectType", "ObjectId");

                    b.HasIndex("ObjectTypeFull", "ObjectId");

                    b.HasIndex("AdditionalDataProcessed", "Version", "CreationDateTime");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLogFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("LogFiles");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLogMessageArgument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("LogMessageArguments");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLogMessageTranslated", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("LogId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.ToTable("LogMessageTranslateds");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint");

                    b.Property<string>("ProcessorKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProcessorKey", "Priority");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhNotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("DispatcherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsCleaned")
                        .HasColumnType("boolean");

                    b.Property<string>("LastFailedMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSendAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<short?>("Priority")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationDeliveries");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActiveDivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockoutStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDivisionId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserAuthRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiryDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("NhUserAuthRefreshToken");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLastRead")
                        .HasColumnType("boolean");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserNotificationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserNotificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserNotificationId");

                    b.ToTable("UserNotificationMessages");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SampleProjectManagement.DAL.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("DivisionId", "Key")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("SampleProjectManagement.DAL.Entities.ProjectTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastModifiedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Title");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivision", null)
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", "ParentOperation")
                        .WithMany("ChildOperations")
                        .HasForeignKey("ParentOperationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserNotification", null)
                        .WithMany()
                        .HasForeignKey("UserNotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentOperation");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationAttempt", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", "Operation")
                        .WithMany("Attempts")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationCheckpoint", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", "Operation")
                        .WithMany("Checkpoints")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationEvent", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", "Operation")
                        .WithMany("Events")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationIdempotencyRecord", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationLease", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", "Operation")
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationStep", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", "Operation")
                        .WithMany("Steps")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationStep", "ParentStep")
                        .WithMany("Children")
                        .HasForeignKey("ParentStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operation");

                    b.Navigation("ParentStep");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionRoleClaim", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionRole", null)
                        .WithMany("DivisionRoleClaims")
                        .HasForeignKey("DivisionRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionUser", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivision", "Division")
                        .WithMany("DivisionUsers")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", "User")
                        .WithMany("DivisionUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionUserRole", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionRole", "DivisionRole")
                        .WithMany("DivisionUserRoles")
                        .HasForeignKey("DivisionRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionUser", "DivisionUser")
                        .WithMany("DivisionUserRoles")
                        .HasForeignKey("DivisionUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DivisionRole");

                    b.Navigation("DivisionUser");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLog", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Division");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLogFile", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLog", null)
                        .WithMany("Files")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLogMessageArgument", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLog", null)
                        .WithMany("MessageArguments")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLogMessageTranslated", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLog", null)
                        .WithMany("MessageTranslateds")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhNotification", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhNotificationDelivery", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhNotification", "Notification")
                        .WithMany("Deliveries")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivision", "ActiveDivision")
                        .WithMany()
                        .HasForeignKey("ActiveDivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveDivision");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserAuthRefreshToken", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany("AuthRefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserNotification", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserNotificationMessage", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserNotification", "UserNotification")
                        .WithMany("Messages")
                        .HasForeignKey("UserNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNotification");
                });

            modelBuilder.Entity("SampleProjectManagement.DAL.Entities.Project", b =>
                {
                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivision", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Division");

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("SampleProjectManagement.DAL.Entities.ProjectTask", b =>
                {
                    b.HasOne("SampleProjectManagement.DAL.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperation", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Checkpoints");

                    b.Navigation("ChildOperations");

                    b.Navigation("Events");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhBackgroundOperationStep", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivision", b =>
                {
                    b.Navigation("DivisionUsers");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionRole", b =>
                {
                    b.Navigation("DivisionRoleClaims");

                    b.Navigation("DivisionUserRoles");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhDivisionUser", b =>
                {
                    b.Navigation("DivisionUserRoles");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhLog", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("MessageArguments");

                    b.Navigation("MessageTranslateds");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhNotification", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUser", b =>
                {
                    b.Navigation("AuthRefreshTokens");

                    b.Navigation("DivisionUsers");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("NewHeap.Platform.AspNet.Common.DAL.Entities.NhUserNotification", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SampleProjectManagement.DAL.Entities.Project", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
