<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>
        <Authors>NewHeap B.V.</Authors>
        <Company>NewHeap B.V.</Company>
        <Product>HIP WebAPI</Product>
        <Copyright>Siers Groep B.V.</Copyright>
        <UserSecretsId>a821b2e7-9787-421c-85f9-4a8e5443f12f</UserSecretsId>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="ContentDynamic\**" />
        <Compile Remove="Models\Binding\**" />
        <Content Remove="ContentDynamic\**" />
        <Content Remove="Models\Binding\**" />
        <EmbeddedResource Remove="ContentDynamic\**" />
        <EmbeddedResource Remove="Models\Binding\**" />
        <None Remove="ContentDynamic\**" />
        <None Remove="Models\Binding\**" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Properties\launchSettings.json" />
    </ItemGroup>


    <ItemGroup>
        <Folder Include="wwwroot\images\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AutoMapper" />
        <PackageReference Include="AutoMapper.Collection" />
        <PackageReference Include="Azure.Identity" />
        <PackageReference Include="EPPlus" />
        <PackageReference Include="Hangfire" />
        <PackageReference Include="Hangfire.Console" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" />
        <PackageReference Include="Microsoft.Extensions.Localization" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="StackExchange.Utils.Configuration" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="System.Formats.Asn1" />
        <PackageReference Include="System.IO.Pipelines" />
        <PackageReference Include="System.Linq.Dynamic.Core" />
        <PackageReference Include="System.Net.Http" />
        <PackageReference Include="System.Text.Json" />
        <PackageReference Include="System.Text.RegularExpressions" />
    </ItemGroup>

    <ItemGroup>
        <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Libraries\NewHeap.Platform.Media.FileStructureStorage.SqlServer\NewHeap.Platform.Media.FileStructureStorage.SqlServer.csproj" />
        <ProjectReference Include="..\..\Libraries\NewHeap.Platform.Media.Http\NewHeap.Platform.Media.Http.csproj" />
        <ProjectReference Include="..\..\Libraries\NewHeap.Platform.Media.MediaStorage.FileSystem\NewHeap.Platform.Media.MediaStorage.FileSystem.csproj" />
        <ProjectReference Include="..\..\Libraries\NewHeap.Platform.Media.Core\NewHeap.Platform.Media.Core.csproj" />
        <ProjectReference Include="..\..\Libraries\NewHeap.Platform.AspNet.Common\NewHeap.Platform.AspNet.Common.csproj" />
    </ItemGroup>

    <ProjectExtensions>
        <VisualStudio>
            <UserProperties appsettings_1Production_1json__JSONSchema="" appsettings_1json__JSONSchema="" appsettings_1Staging_1json__JSONSchema="" />
        </VisualStudio>
    </ProjectExtensions>

</Project>
